# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled2.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EORnhsDYzO5KLRphrvu9ZYyucOKh15ez
"""

import pandas as pd
royhat={
"Ism":["Zulayho","Ali","Vali"],
"Familiya":["Qadamova","Aliyev","Valiyev"],
"Yoshi":[29,15,20],
"Manzili":["Farg'ona shahar","Qo'qon shahar","Faerg'ona shahar"],
"Jinsi":["Ayol","Erkak","Erkak"]
}
jadval=pd.DataFrame(royhat)
print(jadval)
filtr=jadval[jadval["Jinsi"]=="Ayol"]
print(filtr)
filtr=jadval[jadval["Manzili"]=="Qo'qon shahar"]
print(filtr)
filtr=jadval[jadval["Yoshi"]>=15]
print(filtr)
yildankeyin=jadval['Yoshi']+9
print(yildankeyin)